import type { IncidentReport, GoogleEventInfo } from '../types';

export async function createReviewMeeting(accessToken: string, report: IncidentReport): Promise<GoogleEventInfo> {
  const now = new Date();
  const nextDay = new Date(now.getTime() + 24 * 60 * 60 * 1000);
  nextDay.setHours(10, 0, 0, 0);
  const endTime = new Date(nextDay.getTime() + 60 * 60 * 1000);

  const event = {
    summary: `[Post-Mortem] ${report.title}`,
    description: `Incident Review Meeting

Severity: ${report.severity}

Summary:
${report.summary}

Root Causes:
${report.rootCauses.map((c, i) => `${i + 1}. ${c}`).join('\n')}

Action Items:
${report.actionItems.map((a, i) => `${i + 1}. [${a.priority}] ${a.task}`).join('\n')}

---
Generated by AegisOps`,
    start: { dateTime: nextDay.toISOString(), timeZone: 'Asia/Seoul' },
    end: { dateTime: endTime.toISOString(), timeZone: 'Asia/Seoul' },
    reminders: { useDefault: false, overrides: [{ method: 'popup', minutes: 30 }] },
  };

  const res = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
    method: 'POST',
    headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
    body: JSON.stringify(event),
  });

  const data = await res.json();
  return { id: data.id, url: data.htmlLink };
}

export const CalendarService = { createReviewMeeting };
export default CalendarService;