import type { IncidentReport, GoogleDocInfo } from '../types';
import { googleApiFetch, googleApiJson } from './googleApiClient';

export async function createPostMortemDoc(accessToken: string, report: IncidentReport): Promise<GoogleDocInfo> {
  const doc = await googleApiJson<any>({
    accessToken,
    label: 'Google Docs create document',
    url: 'https://docs.googleapis.com/v1/documents',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ title: `[${report.severity}] ${report.title} - Post-Mortem` }),
  });
  const docId = String(doc.documentId || '').trim();
  if (!docId) {
    throw new Error('Google Docs API returned no documentId.');
  }

  const content = `[${report.severity}] ${report.title}

SUMMARY
${report.summary}

IMPACT
- Users Affected: ${report.impact?.estimatedUsersAffected || 'N/A'}
- Duration: ${report.impact?.duration || 'N/A'}
- Peak Latency: ${report.impact?.peakLatency || 'N/A'}
- Peak Error Rate: ${report.impact?.peakErrorRate || 'N/A'}

TIMELINE
${report.timeline.map((t) => `• ${t.time} - ${t.description}`).join('\n')}

ROOT CAUSES
${report.rootCauses.map((c, i) => `${i + 1}. ${c}`).join('\n')}

ACTION ITEMS
${report.actionItems.map((a, i) => `${i + 1}. [${a.priority}] ${a.task}${a.owner ? ` → ${a.owner}` : ''}`).join('\n')}

MITIGATION STEPS
${report.mitigationSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

PREVENTION RECOMMENDATIONS
${report.preventionRecommendations?.map((p, i) => `${i + 1}. ${p}`).join('\n') || 'N/A'}

LESSONS LEARNED
${report.lessonsLearned || 'N/A'}

---
Generated by AegisOps - AI-Powered Incident Analysis
Tags: ${report.tags.join(', ')}`;

  await googleApiFetch({
    accessToken,
    label: 'Google Docs batchUpdate',
    url: `https://docs.googleapis.com/v1/documents/${docId}:batchUpdate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      requests: [{ insertText: { location: { index: 1 }, text: content } }],
    }),
  });

  return {
    id: docId,
    name: String(doc.title || `[${report.severity}] ${report.title} - Post-Mortem`),
    url: `https://docs.google.com/document/d/${docId}/edit`,
  };
}

export const DocsService = { createPostMortemDoc };
export default DocsService;
