import type { IncidentReport, ExportFormat } from '../types';

export function exportReport(report: IncidentReport, format: ExportFormat) {
  const ts = new Date().toISOString().split('T')[0];
  const name = report.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 20);

  if (format === 'json') {
    return { content: JSON.stringify(report, null, 2), filename: `${ts}_${name}.json`, mimeType: 'application/json' };
  }

  if (format === 'markdown') {
    const md = `# ${report.title}\n\n**Severity:** ${report.severity}\n\n## Summary\n${report.summary}\n\n## Impact\n- Users: ${report.impact?.estimatedUsersAffected || 'N/A'}\n- Duration: ${report.impact?.duration || 'N/A'}\n\n## Timeline\n${report.timeline.map((t) => `- **${t.time}** ${t.description}`).join('\n')}\n\n## Root Causes\n${report.rootCauses.map((r, i) => `${i + 1}. ${r}`).join('\n')}\n\n## Action Items\n${report.actionItems.map((a) => `- [${a.priority}] ${a.task}${a.owner ? ` → ${a.owner}` : ''}`).join('\n')}\n\n## Prevention\n${report.preventionRecommendations?.map((p, i) => `${i + 1}. ${p}`).join('\n') || 'N/A'}\n\n---\n*Generated by AegisOps*`;
    return { content: md, filename: `${ts}_${name}.md`, mimeType: 'text/markdown' };
  }

  if (format === 'slack') {
    const emoji: Record<string, string> = { SEV1: '🔴', SEV2: '🟠', SEV3: '🟡', UNKNOWN: '⚪' };
    const blocks = {
      blocks: [
        { type: 'header', text: { type: 'plain_text', text: `${emoji[report.severity]} [${report.severity}] ${report.title}` } },
        { type: 'section', text: { type: 'mrkdwn', text: `*Summary:*\n${report.summary}` } },
        { type: 'section', fields: [
          { type: 'mrkdwn', text: `*Users:*\n${report.impact?.estimatedUsersAffected || 'N/A'}` },
          { type: 'mrkdwn', text: `*Duration:*\n${report.impact?.duration || 'N/A'}` },
        ]},
        { type: 'section', text: { type: 'mrkdwn', text: `*Root Causes:*\n${report.rootCauses.map((r) => `• ${r}`).join('\n')}` } },
      ],
    };
    return { content: JSON.stringify(blocks, null, 2), filename: `${ts}_slack.json`, mimeType: 'application/json' };
  }

  const jira = `h1. ${report.title}\n\n||Severity|${report.severity}||\n\nh2. Summary\n${report.summary}\n\nh2. Root Causes\n${report.rootCauses.map((r) => `# ${r}`).join('\n')}\n\nh2. Actions\n||Priority||Task||Owner||\n${report.actionItems.map((a) => `|${a.priority}|${a.task}|${a.owner || 'TBD'}|`).join('\n')}`;
  return { content: jira, filename: `${ts}_jira.txt`, mimeType: 'text/plain' };
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([content], { type: mimeType }));
  a.download = filename;
  a.click();
}

export const ExportService = { exportReport, copyToClipboard, downloadFile };
export default ExportService;